version: '2'
services:
  nginx:
   container_name: some-nginx
   image: linuxautomations/nginx 
   restart: always
   ports:
   - 80:80
   - 443:443
  mongodb:
    container_name: some-mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    restart: always
    image: linuxautomations/app
    expose:
      - "8080"
    depends_on:
      - nginx
      - mongodb

