apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: mongodbappdeploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodbapp
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: linuxautomations/nginx:v6
          ports:
            - containerPort: 80
          
        - name: mongodb
          image: mongo:3.6
          env:
            - name: MONGO_LOG_DIR
              value: /dev/null
          ports:
            - containerPort: 27017
          command:
            - "mongod"

        - name: app
          imagePullPolicy: Always
          image: linuxautomations/app:v6
          ports:
            - containerPort: 8080
